# -*- coding: utf-8 -*-
"""Mapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6C96agZTBEC3WtE8kY-BF_sP7mMA0Vl
"""

#!/usr/bin/env python3
import sys

current_word = None
current_count = 0

for line in sys.stdin:
    word, count = line.strip().split("\t")
    count = int(count)

    if current_word == word:
        current_count += count
    else:
        if current_word:
            print(f"{current_word}\t{current_count}")  # Print word count
        current_word = word
        current_count = count

# Print the last word count
if current_word:
    print(f"{current_word}\t{current_count}")